name: Atualizar EPG

on:
  schedule:
    # Roda todo dia às 22:00 UTC (19:00 no horário de Brasília -3)
    - cron: '0 22 * * *'
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Rodar script para gerar EPG
      run: node index.js

    - name: Commit e push do arquivo epg.xml
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git diff --quiet && echo "Sem alterações no epg.xml" || git commit -m "Atualiza EPG automático"
        git push
