name: Atualizar EPG 4x por dia

on:
  schedule:
    # A cada 6 horas: 0 0,6,12,18 * * *
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: # Permite rodar manualmente pelo GitHub também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Rodar script de atualização EPG
      run: node index.js

    - name: Commit e push do epg.xml atualizado
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git diff --quiet && echo "Nenhuma alteração no epg.xml" || (git commit -m "Atualização automática do EPG" && git push)
