name: Update EPG

on:
  schedule:
    - cron: '0 */4 * * *' # Atualiza a cada 4 horas
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Gerar EPG
        run: node index.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push do novo EPG
        run: |
          git add epg.xml
          git commit -m "EPG atualizado automaticamente"
          git push
        continue-on-error: true
