name: Atualizar EPG mi-tv-scraper

on:
  schedule:
    - cron: '0 0,6,12,18 * * *' # 4x por dia UTC: 00h, 06h, 12h, 18h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependências
      run: npm install

    - name: Rodar index.js para gerar epg.xml
      run: node index.js

    - name: Commit e push se epg.xml mudou
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git diff --cached --quiet || git commit -m "Atualização automática do EPG"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
